# Generated by Django 4.0 on 2023-07-23 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0002_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='votecontext',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vote.user'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vote.user'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='vote_context',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='vote.votecontext'),
        ),
    ]
