
- hosts: d-pipeline
  remote_user: ubuntu
  become: true
  roles:
    - jenkins

# - hosts: d-analysis
#   remote_user: ubuntu
#   become: true
#   roles:
#     - sonarqube-preprocess

# - hosts: d-analysis
#   remote_user: ubuntu
#   become: true
#   roles:
#     - sonarqube-install